### ISSUE TITLE
// TODO

### ISSUE THREAD

**Issue by Winter259** [Winter259/arma-bot#1]
// TODO:
- [ ] In general
 - [ ] Convert to PEP8 standard 
 - [ ] Update readme to include all required libraries
- [ ] Technical
 - [ ] Consider less data intensive way of checking for updates rather than grabbing the whole JSON feed every time (via rss?)
